### PR TITLE
#116 (Migrate `order` microservice to latest `minos` version)

### PR DESCRIPTION
**Pull request by garciparedes**

### CODE REVIEW

**Review by vladyslav-fenchak — APPROVED** [review]

**Review by albamig — CHANGES_REQUESTED** [review]
Everything works fine except when an empty list is passed:

```bash 
curl -X POST localhost:5566/orders -H "Content-Type: application/json" -d '{"product_uuids": []}'
```

The following exception trace is raised:
```python
2021-07-27 09:53:42 [T:MainThread] ERROR:minos.networks.rest.builders: Raised an exception: ValueError('Given field type is not supported: None').
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/minos/saga/manager.py", line 147, in _run_with_pause_on_disk
    await execution.execute(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/minos/saga/executions/saga.py", line 175, in execute
    await self._execute_one(execution_step, reply_topic=reply_topic, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/minos/saga/executions/saga.py", line 192, in _execute_one
    raise exc
  File "/usr/local/lib/python3.9/site-packages/minos/saga/executions/saga.py", line 183, in _execute_one
    self.context = await execution_step.execute(self.context, execution_uuid=self.uuid, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/minos/saga/executions/step.py", line 81, in execute
    context = await self._execute_on_reply(context, reply, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/minos/saga/executions/step.py", line 109, in _execute_on_reply
    raise exc
  File "/usr/local/lib/python3.9/site-packages/minos/saga/executions/step.py", line 106, in _execute_on_reply
    context = await executor.exec(self.definition.on_reply_operation, context, reply)
  File "/usr/local/lib/python3.9/site-packages/minos/saga/executions/executors/on_reply.py", line 51, in exec
    raise MinosSagaPausedExecutionStepException()
minos.saga.exceptions.MinosSagaPausedExecutionStepException: There was a pause while 'SagaExecutionStep' was executing.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/minos/networks/rest/builders.py", line 150, in _fn
    response = await response
  File "/usr/local/lib/python3.9/site-packages/minos/networks/decorators/builders.py", line 114, in _wrapped_fn
    return await _awaitable_fn(request)
  File "/usr/local/lib/python3.9/site-packages/minos/networks/decorators/definitions/abc.py", line 51, in _wrapper
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/minos/networks/decorators/definitions/abc.py", line 51, in _wrapper
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/src/commands/services.py", line 46, in create_order
    uuid = await self.saga_manager.run("CreateOrder", context=SagaContext(product_uuids=product_uuids))
  File "/usr/local/lib/python3.9/site-packages/minos/common/saga.py", line 47, in run
    return await self._run_new(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/minos/saga/manager.py", line 112, in _run_new
    return await self._run(execution, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/minos/saga/manager.py", line 128, in _run
    await self._run_with_pause_on_disk(execution, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/minos/saga/manager.py", line 149, in _run_with_pause_on_disk
    self.storage.store(execution)
  File "/usr/local/lib/python3.9/site-packages/minos/saga/executions/storage.py", line 68, in store
    value = execution.raw
  File "/usr/local/lib/python3.9/site-packages/minos/saga/executions/saga.py", line 257, in raw
    "context": self.context.avro_str,
  File "/usr/local/lib/python3.9/site-packages/minos/common/model/abc.py", line 255, in avro_str
    return b64encode(self.avro_bytes).decode()
  File "/usr/local/lib/python3.9/site-packages/minos/common/model/abc.py", line 264, in avro_bytes
    return MinosAvroProtocol().encode(self.avro_data, self.avro_schema)
  File "/usr/local/lib/python3.9/site-packages/minos/common/meta.py", line 32, in __get__
    return self.fget.__get__(obj, klass)()
  File "/usr/local/lib/python3.9/site-packages/minos/common/model/abc.py", line 238, in avro_schema
    return [AvroSchemaEncoder("", self_or_cls.model_type).build()["type"]]
  File "/usr/local/lib/python3.9/site-packages/minos/common/model/serializers/avro_schema_encoder.py", line 83, in build
    return {"name": self._name, "type": self._build_schema(self._type)}
  File "/usr/local/lib/python3.9/site-packages/minos/common/model/serializers/avro_schema_encoder.py", line 88, in _build_schema
    return self._build_single_schema(type_field)
  File "/usr/local/lib/python3.9/site-packages/minos/common/model/serializers/avro_schema_encoder.py", line 139, in _build_single_schema
    return self._build_model_type_schema(type_field)
  File "/usr/local/lib/python3.9/site-packages/minos/common/model/serializers/avro_schema_encoder.py", line 154, in _build_model_type_schema
    "fields": [AvroSchemaEncoder(k, v).build() for k, v in type_field.type_hints.items()],
  File "/usr/local/lib/python3.9/site-packages/minos/common/model/serializers/avro_schema_encoder.py", line 154, in <listcomp>
    "fields": [AvroSchemaEncoder(k, v).build() for k, v in type_field.type_hints.items()],
  File "/usr/local/lib/python3.9/site-packages/minos/common/model/serializers/avro_schema_encoder.py", line 83, in build
    return {"name": self._name, "type": self._build_schema(self._type)}
  File "/usr/local/lib/python3.9/site-packages/minos/common/model/serializers/avro_schema_encoder.py", line 88, in _build_schema
    return self._build_single_schema(type_field)
  File "/usr/local/lib/python3.9/site-packages/minos/common/model/serializers/avro_schema_encoder.py", line 144, in _build_single_schema
    return self._build_composed_schema(type_field)
  File "/usr/local/lib/python3.9/site-packages/minos/common/model/serializers/avro_schema_encoder.py", line 171, in _build_composed_schema
    return self._build_list_schema(type_field)
  File "/usr/local/lib/python3.9/site-packages/minos/common/model/serializers/avro_schema_encoder.py", line 182, in _build_list_schema
    return {"type": AVRO_ARRAY, "items": self._build_schema(get_args(type_field)[0])}
  File "/usr/local/lib/python3.9/site-packages/minos/common/model/serializers/avro_schema_encoder.py", line 88, in _build_schema
    return self._build_single_schema(type_field)
  File "/usr/local/lib/python3.9/site-packages/minos/common/model/serializers/avro_schema_encoder.py", line 144, in _build_single_schema
    return self._build_composed_schema(type_field)
  File "/usr/local/lib/python3.9/site-packages/minos/common/model/serializers/avro_schema_encoder.py", line 179, in _build_composed_schema
    raise ValueError(f"Given field type is not supported: {type_field}")  # pragma: no cover
ValueError: Given field type is not supported: None
```

**Review by albamig — APPROVED** [review]
We've come to agree this error is raised in a different place, so this issue is ok.
@garciparedes will create a new issue in the appropriate repository.

Well done!!

**Comment by garciparedes** [comment]
Hi @albamig, thanks for your help while trying to understand the obtained error. 😉 

Here is a minimum reproducible case:
```python
SagaContext(lst=[]).avro_bytes
```
However, I suspect that the bug is not directly related with `minos.saga.SagaContext`, but with the `minos.common.AvroSchemaEncoder`. In any case, I'll examine the code and create an issue to fix it on the guilty package.

**Comment by garciparedes** [comment]
Hahaha, I went deeper and found the real cause of this bug. In summary, the `minos.common.TypeHintBuilder`, which has the responsibility to get the type hints from a given value, is not being able to find the proper one for `[]` (empty lists).

This bug will be resolved by https://github.com/Clariteia/minos_microservice_common/issues/462 🎉

**Comment by albamig** [comment]
Great! Nice catch @garciparedes

**Pull request merged**
